# vim:ft=kitty

# The amount of time (in ms) the cursor must be stationary before the cursor trail becomes visible
cursor_trail 750
# The decay rate of the cursor trail; controls how quickly the trail fades
cursor_trail_decay 0.1 0.4
# The minimum number of cells the cursor has to move before starting the trail
cursor_trail_start_threshold 5
