#!/bin/bash -e
case $1 in
light | dark)
  value=prefer-$1
  echo setting gsettings preferred color scheme to \'$value\'
  gsettings set org.gnome.desktop.interface color-scheme $value
  for program in kitty nvim i3status-rust mako sway; do
    ~/.config/$program/scripts/set-theme
  done
  makoctl reload
  exit 0
  ;;
*)
  echo 'Unknown theme "'$theme'"'
  exit 1
  ;;
esac
