eDP-1:
  light: /usr/share/backgrounds/anime-landscape.jpg
  dark: /usr/share/backgrounds/leaves.jpg
"desc:Samsung Electric Company Odyssey G95NC HNTX600649":
  light: /usr/share/backgrounds/seaside-house.jpg
  dark: /usr/share/backgrounds/red-green-leaves.jpg
